### ISSUE TITLE
Operations starts with a massive negative generation?  

### ISSUE THREAD

**Issue by bruttkay-cmd** [MartinStoffel/tigo#8]
12 panes on Energy dashboard, at 6:00 o'clock 

![image](https://github.com/user-attachments/assets/76a8fda0-b36f-475b-ae86-c5818046e848)

**Comment by MartinStoffel** [comment]
Does this happen every day? Or just the first day after you enabled/installed the integration.

Frankly, I currently have no idea why that happens. The integration get's the data from the api and just sends that to home assistant. Might be, that if you install it when there is no production, then you might have this strange effect. 

By the way, how did you create this chart? Is it right from home assistant?

**Comment by bruttkay-cmd** [comment]
Hi Martin,

I have the issue every day. Tigo own interface shows the correct figure.
Yes, I might have connected overnight.
The dashboard is the built in energy dashboard an d I have added the Tigo panels one by one to it.
Let me know if you find something. 

Ps: I also added grid meters data to the Energy usage part coming back from the DSO system, but this datasource has not been added to solar production…

**Comment by bruttkay-cmd** [comment]
I have also made a little experiment.  The Energy Dashboard is looking for: Configure solar panels
Pick a sensor which measures solar energy production in either of cal, Gcal, GJ, J, kcal, kJ, kWh, Mcal, MJ, MWh, Wh.

Beside that I picked up a simple panel A1 and Tigo sensors showing the following values:

![Screenshot 2024-10-31 153619](https://github.com/user-attachments/assets/48c47e7c-7beb-485f-ab68-13236395e6ce)
![Screenshot 2024-10-31 153448](https://github.com/user-attachments/assets/db2c7ab2-6b5f-4a4e-a838-086708485742)

**Comment by MartinStoffel** [comment]
Thank you for pointing to this. Please update the integration and let me know if it now works.

Background:
Tigo resets it's counter every day, so the massive negative consumption you observed was the sum of yesterdays production.

**Comment by bruttkay-cmd** [comment]
For today the negative column is already in (all history stored in HA) so I will let you know tomorrow, if there is no chance to reset the database or reinitiate history download.

**Comment by MartinStoffel** [comment]
@bruttkay-cmd  did the fix work for you, or does the energy dashboard still show negative generation?
